### ISSUE TITLE
400: Duplicate records found. Connection is in request state but not able to accept connection. Happening randomly for a few connections.

### ISSUE THREAD

**Issue by itsdheerajbudhiraja** [openwallet-foundation/acapy#1826]
Randomly some connections are failing while --auto-accept is enabled and not able to perform manual connection also for that connection ID. Below are API responses: 

/connections/{conn_id} 
```
{
  "connection_id": "c09b8f79-cca4-4b5b-abee-07360663efa6",
  "updated_at": "2022-06-20T14:17:03.706998Z",
  "created_at": "2022-06-20T14:16:09.563740Z",
  "connection_protocol": "connections/1.0",
  "accept": "manual",
  "state": "request",
  "their_role": "invitee",
  "invitation_key": "FPcvfW8ZFTHfbqmz21QapDRzo52oQoEbxigca3Xar1c8",
  "rfc23_state": "request-received",
  "their_label": "dbdagr8",
  "routing_state": "none",
  "their_did": "9sXr12YBPYbVx4LCR9PpE9",
  "invitation_mode": "once"
}
```

/connections/c09b8f79-cca4-4b5b-abee-07360663efa6/accept-request : 

```
400: Duplicate records found.
```
Following are exception logs: 
```
2022-06-20 14:50:16,160 aries_cloudagent.admin.server ERROR Handler error with exception: Duplicate records found.

=================
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/connections/v1_0/routes.py", line 665, in connections_accept_request
    response = await connection_mgr.create_response(connection, my_endpoint)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/connections/v1_0/manager.py", line 688, in create_response
    request = await connection.retrieve_request(session)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/connections/models/conn_record.py", line 473, in retrieve_request
    self.RECORD_TYPE_REQUEST, {"connection_id": self.connection_id}
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/storage/base.py", line 94, in find_record
    raise StorageDuplicateError("Duplicate records found")
aries_cloudagent.storage.error.StorageDuplicateError: Duplicate records found
```

**Comment by itsdheerajbudhiraja** [comment]
@shaangill025  10 number of connections is very small number to replicate the issue.

As I mentioned this issue is coming randomly for afew connections. We have more than 2000 connections already in db, and this happens 1 in 300-400 connections.

Seems because of some asynchronous behaviour some entry in wallet is duplicated or corrupted.

I tried to see the connection flow code, will try to find again where exactly that corruption is happening.

**Comment by miroslav-inc** [comment]
This can occur when you setup both --auto-accept-invites in aries agent and also manually accept from webhook events

**Comment by Ennovate-com** [comment]
This also happens if the auto_accept fails for some reason and you try to accept the connection request manually. I'm not yet sure why the auto_accept is occasionally failing.

@dbluhm
Question: If there is a connection in a "request_received" state (example below), should we be allowed to try the "accept-request", or do we have to delete the connection record and start all over with the out-of-band messages?

```{
  "results": [
    {
      "state": "request",
      "created_at": "2023-09-20T12:59:02.196758Z",
      "updated_at": "2023-09-20T13:43:32.072534Z",
      "connection_id": "72a8c6cd-8956-44af-8694-5967e9a1910e",
      "my_did": "5p6pTY2hpxjdBy2GnzZdnT",
      "their_did": "UL7EuR1V9cv2idokK8WWD4",
      "their_label": "Bob",
      "their_role": "invitee",
      "connection_protocol": "didexchange/1.0",
      "rfc23_state": "request-received",
      "invitation_key": "AXrSHe6P4vTknk9U1aeScq9Mv44YUMhm65JrtvqMpWVE",
      "invitation_msg_id": "03eecb11-fe96-471e-947c-e100e9929d02",
      "request_id": "5cf90b5d-2ce0-4a4b-a33a-71c7660d74b1",
      "accept": "auto",
      "invitation_mode": "once",
      "alias": "Alice"
    }
]```

Using `their_did` from the connection above, the `find_record` call:
```  type_filter = 'did_doc'
  their_did = 'UL7EuR1V9cv2idokK8WWD4'
  tagQueryMapping: Mapping[str, str] = {
    'did': their_did
  }
  logging.info(f'Getting storage record type_filter: {type_filter} their_did: {their_did}')
  storageRecord = await storage.find_record(type_filter, tagQueryMapping)```

results in:
```INFO:aries_askar.native.aries_askar.ffi.store:	src/ffi/store.rs:214 | Opened store StoreHandle(1)
INFO:aries_askar.native.aries_askar.ffi.store:	src/ffi/store.rs:528 | Started session SessionHandle(1) on store StoreHandle(1) (txn: false)
INFO:root:Getting storage record type_filter: did_doc their_did: UL7EuR1V9cv2idokK8WWD4
INFO:aries_askar.native.aries_askar.backend.db_utils:	src/backend/db_utils.rs:103 | Acquire pool connection
Traceback (most recent call last):
  File "/home/robs/GitRepositories/did-agent/askar.py", line 71, in <module>
    asyncio.run(main())
  ...
  File "/usr/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/home/robs/GitRepositories/did-agent/askar.py", line 67, in main
    storageRecord = await storage.find_record(type_filter, tagQueryMapping, optionsMapping)
  File "/home/robs/GitRepositories/did-agent/aries_cloudagent/storage/askar.py", line 161, in find_record
    raise StorageDuplicateError("Duplicate records found")
aries_cloudagent.storage.error.StorageDuplicateError: Duplicate records found```

The `Duplicate records found` error occurs with or without `my_endpoint`
<img width="765" alt="Screenshot 2023-09-20 at 3 02 18 PM" src="https://github.com/hyperledger/aries-cloudagent-python/assets/104096338/76600967-4f81-4dcb-8bb3-1eeb6fc466b7">
