### ISSUE TITLE
Did rotation to did:web throw ClassNotFoundError

### ISSUE THREAD

**Issue by Lab3ss** [openwallet-foundation/acapy#3381]
I got two wallets with a connection between. Currently working with did:peer I try to rotate to did:web. Acapy throws the following error. The contact behind the connection never receive the webhook to be notified about the did rotation.

```
2024-12-05 16:59:13,586 acapy_agent.protocols.routing.v1_0.manager INFO >>> FOUND routing record for verkey: Exq8qn15sY45YRepvFXCsvJcAq7Dv61ccuLbMXQfh9wR
2024-12-05 16:59:13,603 acapy_agent.transport.pack_format DEBUG Expanded message: {'@type': 'https://didcomm.org/did-rotate/1.0/ack', '@id': '529817e5-348d-433c-bb64-322b9da956af', '~thread': {'thid': 'd82ab65f-30ae-4daa-8411-2b98164a2652'}, 'status': 'OK'}
2024-12-05 16:59:13,604 aiohttp.access INFO 127.0.0.1 [05/Dec/2024:16:59:13 +0000] "POST / HTTP/1.1" 200 112 "-" "Python/3.12 aiohttp/3.10.10"
2024-12-05 16:59:13,605 acapy_agent.core.conductor ERROR Exception in message handler:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/home/aries/.local/lib/python3.12/site-packages/acapy_agent/core/dispatcher.py", line 192, in handle_v1_message
    message = await self.make_message(profile, inbound_message.payload)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aries/.local/lib/python3.12/site-packages/acapy_agent/core/dispatcher.py", line 312, in make_message
    message_cls = message_cls.resolved
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/aries/.local/lib/python3.12/site-packages/acapy_agent/utils/classloader.py", line 197, in resolved
    self._inst = ClassLoader.load_class(self._cls_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aries/.local/lib/python3.12/site-packages/acapy_agent/utils/classloader.py", line 110, in load_class
    raise ClassNotFoundError(
acapy_agent.utils.classloader.ClassNotFoundError: Class 'Ack' not defined in module: acapy_agent.protocols.did_rotate.v1_0.messages.ack
2024-12-05 16:59:13,607 acapy_agent.core.conductor ERROR DON'T shutdown on ClassNotFoundError Class 'Ack' not defined in module: acapy_agent.protocols.did_rotate.v1_0.messages.ack
2024-12-05 16:59:13,607 acapy_agent.core.dispatcher ERROR Handler error: Dispatcher.handle_v1_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/home/aries/.local/lib/python3.12/site-packages/acapy_agent/core/dispatcher.py", line 192, in handle_v1_message
    message = await self.make_message(profile, inbound_message.payload)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aries/.local/lib/python3.12/site-packages/acapy_agent/core/dispatcher.py", line 312, in make_message
    message_cls = message_cls.resolved
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/aries/.local/lib/python3.12/site-packages/acapy_agent/utils/classloader.py", line 197, in resolved
    self._inst = ClassLoader.load_class(self._cls_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aries/.local/lib/python3.12/site-packages/acapy_agent/utils/classloader.py", line 110, in load_class
    raise ClassNotFoundError(
acapy_agent.utils.classloader.ClassNotFoundError: Class 'Ack' not defined in module: acapy_agent.protocols.did_rotate.v1_0.messages.ack
```
Am I using did rotation incorrectly ?

**Comment by ff137** [comment]
Will be resolved by #3380
